site_name: napari-denoiseg
site_description: A napari plugin for self-supervised denoising and segmentation of microscopy images, using the DenoiSeg method.
site_author: jdeschamps

theme: readthedocs


repo_url: https://github.com/juglab/napari-denoiseg

pages:
- Home: index.md
