site_name: napari-denoiseg
site_description: A napari plugin for supervised denoising and segmentation of microscopy images.
site_author: jdeschamps

theme: readthedocs


repo_url: https://github.com/juglab/napari_denoiseg

pages:
- Home: index.md
