
#labels
AXES = "Axes"
ENABLE_3D = "Enable 3D"
EPOCHS = "# of Epochs"
STEPS = "# of Steps"
BATCH_SIZE = "Batch size"
PATCH_SIZE = "Patch size"
PATCH_SIZE_3D = "Patch Z"
TRAIN_LABEL_PCT = "Train to Label ratio"
THRESHOLD = "Threshold"
THRESHOLD_ENABLE = "Enable threshold"
MODEL = "Select model"
#tooltips
AXES_TOOLTIP = ""
ENABLE_3D_TOOLTIP = ""
EPOCHS_TOOLTIP = ""
STEPS_TOOLTIP = ""
BATCH_SIZE_TOOLTIP = ""
PATCH_SIZE_TOOLTIP = ""
PATCH_SIZE_3D_TOOLTIP = ""
TRAIN_LABEL_PCT_TOOLTIP = ""
THRESHOLD_TOOLTIP = ""
THRESHOLD_ENABLE_TOOLTIP = ""
MODEL_TOOLTIP = ""
#banner info
